FROM node:alpine AS builder

WORKDIR /usr/src/web

ENV NODE_ENV production

COPY package*.json ./
RUN npm install

COPY . .

RUN npm run build

FROM nginx:alpine

COPY --from=builder /usr/src/web/build /usr/share/nginx/html

# CMD /bin/sh -c "exec nginx -g 'daemon off;'"